// This model was generated by Lumber. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const Checklists = sequelize.define('checklists', {
    todoId: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      allowNull: false,
    },
    taskId: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      defaultValue: 0,
      allowNull: false,
    },
    todo: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    isCompleted: {
      type: DataTypes.INTEGER,
      defaultValue: 0,
      allowNull: false,
    },
  }, {
    tableName: 'checklists',
    underscored: true,
    timestamps: false,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v6/reference-guide/relationships#adding-relationships.
  Checklists.associate = (models) => {
    Checklists.belongsTo(models.tasks, {
      foreignKey: {
        name: 'taskIdKey',
        field: 'task_id',
      },
      targetKey: 'taskId',
      as: 'task',
    });
  };

  return Checklists;
};
